"""Question generation domain."""

from .orchestrator import generate_question_paper_tool
from .config import (
    INPUT_FILE_LOCATOR_SUBAGENT,
    BLUEPRINT_VALIDATOR_SUBAGENT,
    CBSE_QUESTION_RETRIEVER_SUBAGENT,
    QUESTION_ASSEMBLER_SUBAGENT,
    PAPER_VALIDATOR_SUBAGENT,
    DOCX_GENERATOR_SUBAGENT,
    ALL_SUBAGENTS,
)

__all__ = [
    "generate_question_paper_tool",
    "INPUT_FILE_LOCATOR_SUBAGENT",
    "BLUEPRINT_VALIDATOR_SUBAGENT",
    "CBSE_QUESTION_RETRIEVER_SUBAGENT",
    "QUESTION_ASSEMBLER_SUBAGENT",
    "PAPER_VALIDATOR_SUBAGENT",
    "DOCX_GENERATOR_SUBAGENT",
    "ALL_SUBAGENTS",
]
